---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnos-backends
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  metrics: "http://192.168.122.169:9009/api/v1/push"
  logs: "http://192.168.122.169:8200"
  traces: "http://192.168.122.169:4317"
