---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-operator
  namespace: cnos-system
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/version: "0.99.0"