apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnos-apm-server
  labels:
    app: cnos-apm-server
  namespace: cnos-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cnos-apm-server
  template:
    metadata:
      labels:
        app: cnos-apm-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 0
        runAsUser: 1000
      serviceAccountName: cnos-apm-server
      volumes:
        - name: cnos-elasticsearch-certs
          secret:
            secretName: cnos-elasticsearch-master-certs
        - name: cnos-apm-server-config
          configMap:
            name: cnos-apm-server-config
            defaultMode: 0600
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 cnos-elasticsearch-master 9200; do echo "Waiting for Elasticsearch"; sleep 10; done' ]
      containers:
        - name: cnos-apm-server
          image: "docker.elastic.co/apm/apm-server:8.13.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cnos-elasticsearch-master-credentials
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cnos-elasticsearch-master-credentials
          securityContext:
            privileged: false
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1000
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 8200
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: cnos-elasticsearch-certs
              mountPath: /usr/share/apm-server/config/certs/
              readOnly: true
            - name: cnos-apm-server-config
              mountPath: /usr/share/apm-server/apm-server.yml
              subPath: apm-server.yml
              readOnly: true
