---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-deployment-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcol-deployment-collector
subjects:
  - kind: ServiceAccount
    name: otelcol-deployment-collector
    namespace: cnos-system
