---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnos-backends
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  metrics: "http://10.55.0.151:9009/api/v1/push"
  logs: "http://10.55.0.151:8200"
  traces: "http://10.55.0.151:4317"
