apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnos-apm-server-cluster-role
  labels:
    app: "cnos-apm-server"
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
