apiVersion: v1
kind: ConfigMap
metadata:
  name: cnos-apm-server-config
  labels:
    app: "cnos-apm-server"
  namespace: cnos-system
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"

    queue: {}

    output.elasticsearch:
      hosts: ["https://cnos-elasticsearch-master:9200"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      ## If SSL is enabled
      protocol: https
      ssl.certificate_authorities: [/usr/share/apm-server/config/certs/ca.crt]
      ssl.certificate: /usr/share/apm-server/config/certs/tls.crt
      ssl.key: /usr/share/apm-server/config/certs/tls.key
