apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-deployment-collector
  labels:
    app.kubernetes.io/version: "0.96.0"
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "services", "replicationcontrollers", "nodes", "endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "daemonsets", "statefulsets", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["config.nephio.org"]
    resources: ["configs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["workload.nephio.org"]
    resources: ["nfconfigs", "nfdeployments"]
    verbs: ["get", "list", "watch"]