apiVersion: batch/v1
kind: Job
metadata:
  name: cnos-jaeger-es-rollover-init
  labels:
    app: cnos-jaeger
  namespace: cnos-system
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: cnos-jaeger
    spec:
      serviceAccountName: cnos-jaeger-es-rollover
      securityContext:
        runAsUser: 1000
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox
          command: [ 'sh', '-c', 'sleep 120 && until nc -z -v -w30 cnos-elasticsearch-master 9200; do echo "Waiting for Elasticsearch"; sleep 10; done' ]
      containers:
        - name: cnos-jaeger-es-rollover-init
          image: jaegertracing/jaeger-es-rollover:1.53.0
          imagePullPolicy: IfNotPresent
          args:
            - init
            - https://cnos-elasticsearch-master.cnos-system:9200
            - --es.tls.ca=/es-tls/ca.crt
          env:
            - name: ES_SERVER_URLS
              value: https://cnos-elasticsearch-master.cnos-system:9200
            - name: ES_USERNAME
              value: elastic
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnos-elasticsearch-master-credentials
                  key: password
            - name: ES_TLS_ENABLED
              value: "true"
            - name: ES_TLS_CA
              value: /es-tls/ca.crt
            - name: ES_TAGS_AS_FIELDS_ALL
              value: "true"
          volumeMounts:
            - name: cnos-elasticsearch-master-certs
              mountPath: /es-tls/
              readOnly: true
      volumes:
        - name: cnos-elasticsearch-master-certs
          secret:
            secretName: cnos-elasticsearch-master-certs
