apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnos-kibana-role
  namespace: cnos-system
  labels:
    app: cnos-kibana
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
