apiVersion: v1
kind: Service
metadata:
  name: cnos-kibana
  labels:
    app: cnos-kibana
  namespace: cnos-system
spec:
  type: LoadBalancer
  ports:
    - port: 5601
      nodePort: 30444
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: cnos-kibana
