apiVersion: v1
kind: ConfigMap
metadata:
  name: cnos-prometheus-conf
  labels:
    name: prometheus-server-conf
  namespace: cnos-system
data:
  prometheus.yml: |-
    global:
      scrape_interval: 2s
      evaluation_interval: 2s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs: []
