---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-deployment
  namespace: cnos-system
  labels:
    info.cnos/cluster-name: example
    nephio.org/region: missing
    nephio.org/site-type: missing
  annotations:
    backends.cnos/remote-metrics: example
    backends.cnos/remote-logs: example
    backends.cnos/remote-traces: example
spec:
  env:
    - name: CLUSTER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['info.cnos/cluster-name']
    - name: REGION
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['nephio.org/region']
    - name: SITE_TYPE
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['nephio.org/site-type']
    - name: REMOTE_BACKEND_METRICS
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['backends.cnos/remote-metrics']
    - name: REMOTE_BACKEND_LOGS
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['backends.cnos/remote-logs']
    - name: REMOTE_BACKEND_TRACES
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['backends.cnos/remote-traces']
  volumeMounts:
    - mountPath: /es-certs/remote
      name: es-certs-remote
  volumes:
    - name: es-certs-remote
      secret:
        secretName: cnos-elasticsearch-remote-certs
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      prometheus:
        config:
          scrape_configs:
            - job_name: 'kube-state-metrics'
              static_configs:
                - targets: [ 'kube-state-metrics.kube-system.svc.cluster.local:8080' ]

      k8s_cluster:
        auth_type: serviceAccount
        node_conditions_to_report: [Ready, NotReady, MemoryPressure]
        allocatable_types_to_report: [cpu, memory, storage]
        distribution: kubernetes
        collection_interval: 10s

      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: certificates
            mode: pull
            group: cert-manager.io/v1
          - name: pods
            mode: pull
          - name: events
            group: events.k8s.io
            mode: watch
          - name: configs
            group: ref.nephio.org/v1alpha1
            mode: pull
          - name: nfconfigs
            group: workload.nephio.org/v1alpha1
            mode: pull
          - name: nfdeployments
            group: workload.nephio.org/v1alpha1
            mode: pull

    processors:
      batch:
        send_batch_size: 10000
        timeout: 1s

      attributes/add-source/k8s_cluster:
        actions:
          - key: otel_data_source
            value: k8s_cluster
            action: upsert

      attributes/add-source/ksm:
        actions:
          - key: otel_data_source
            value: ksm
            action: upsert

      attributes/add-source/k8sobjects:
        actions:
          - key: otel_data_source
            value: k8sobjects
            action: upsert

      attributes/cluster:
        actions:
          - key: cluster
            value: ${env:CLUSTER_NAME}
            action: upsert
          - key: scenario
            value: "no_replication"
            action: upsert
          - key: region
            value: ${env:REGION}
            action: upsert
          - key: site_type
            value: ${env:SITE_TYPE}
            action: upsert

      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

    exporters:
      prometheusremotewrite/remote:
        endpoint: ${env:REMOTE_BACKEND_METRICS}
        tls:
          insecure: true

      otlp/jaeger/remote:
        endpoint: ${env:REMOTE_BACKEND_TRACES}
        tls:
          insecure: true

      otlp/elasticsearch/remote:
        endpoint: ${env:REMOTE_BACKEND_LOGS}
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, attributes/cluster]
          exporters: [otlp/jaeger/remote]

        metrics:
          receivers: [otlp]
          processors: [batch, attributes/cluster]
          exporters: [prometheusremotewrite/remote]
        metrics/k8s_cluster:
          receivers: [k8s_cluster]
          processors: [k8sattributes, batch, attributes/cluster, attributes/add-source/k8s_cluster]
          exporters: [prometheusremotewrite/remote]
        metrics/ksm:
          receivers: [prometheus]
          processors: [k8sattributes, batch, attributes/cluster, attributes/add-source/ksm]
          exporters: [prometheusremotewrite/remote]

        logs:
          receivers: [otlp]
          processors: [batch, attributes/cluster]
          exporters: [otlp/elasticsearch/remote]
        logs/k8sobjects:
          receivers: [k8sobjects]
          processors: [k8sattributes, batch, attributes/cluster, attributes/add-source/k8sobjects]
          exporters: [otlp/elasticsearch/remote]
