apiVersion: v1
kind: ConfigMap
metadata:
  name: cnos-elasticsearch-master-config
  labels:
    app: "cnos-elasticsearch-master"
  namespace: cnos-system
data:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.http.ssl.enabled: true
