apiVersion: v1
kind: Service
metadata:
  name: cnos-jaeger-collector
  labels:
    app: cnos-jaeger
  namespace: cnos-system
spec:
  ports:
    - name: grpc
      port: 14250
      protocol: TCP
      targetPort: grpc
      appProtocol: grpc
    - name: http
      port: 14268
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: otlp-http
    - name: admin
      port: 14269
      targetPort: admin
  selector:
    app: cnos-jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cnos-jaeger-query
  labels:
    app: cnos-jaeger
  namespace: cnos-system
spec:
  ports:
    - name: query
      port: 80
      protocol: TCP
      targetPort: query
      nodePort: 30555
    - name: grpc
      port: 16685
      protocol: TCP
      targetPort: grpc
    - name: admin
      port: 16687
      protocol: TCP
      targetPort: admin
  selector:
    app: cnos-jaeger
  type: LoadBalancer
