apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-deployment
  namespace: cnos-system
  labels:
    cluster-info/cluster-name: nephio
    cluster-info/region: ""
    cluster-info/site-type: management
spec:
  env:
    - name: CLUSTER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['cluster-info/cluster-name']
    - name: REGION
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['cluster-info/region']
    - name: SITE_TYPE
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['cluster-info/site-type']
  volumeMounts:
    - mountPath: /es-certs
      name: es-certs
    - mountPath: /es-certs/remote
      name: es-certs-remote
  volumes:
    - name: es-certs
      secret:
        secretName: cnos-elasticsearch-master-certs
    - name: es-certs-remote
      secret:
        secretName: cnos-elasticsearch-remote-certs
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      k8s_cluster:
        auth_type: serviceAccount
        node_conditions_to_report: [Ready, NotReady, MemoryPressure]
        allocatable_types_to_report: [cpu, memory, storage]
        distribution: kubernetes
        collection_interval: 10s

      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: certificates
            mode: pull
            group: cert-manager.io/v1
          - name: pods
            mode: pull
          - name: events
            group: events.k8s.io
            mode: watch
          - name: networks
            group: config.nephio.org/v1alpha1
          - name: workloadclusters
            group: infra.nephio.org/v1alpha1
            mode: pull
          - name: networks
            group: config.nephio.org/v1alpha1
            mode: pull
          - name: clustercontexts
            group: infra.nephio.org/v1alpha1
            mode: pull
          - name: networkconfigs
            group: infra.nephio.org/v1alpha1
            mode: pull
          - name: networks
            group: infra.nephio.org/v1alpha1
            mode: pull
          - name: repositories
            group: infra.nephio.org/v1alpha1
            mode: pull
          - name: tokens
            group: infra.nephio.org/v1alpha1
            mode: pull
          - name: endpoints
            group: inv.nephio.org/v1alpha1
            mode: pull
          - name: links
            group: inv.nephio.org/v1alpha1
            mode: pull
          - name: nodes
            group: inv.nephio.org/v1alpha1
            mode: pull
          - name: targets
            group: inv.nephio.org/v1alpha1
            mode: pull
          - name: ipclaims
            group: ipam.resource.nephio.org/v1alpha1
            mode: pull
          - name: ipprefixes
            group: ipam.resource.nephio.org/v1alpha1
            mode: pull
          - name: networkinstances
            group: ipam.resource.nephio.org/v1alpha1
            mode: pull
          - name: capacities
            group: req.nephio.org/v1alpha1
            mode: pull
          - name: datanetworknames
            group: req.nephio.org/v1alpha1
            mode: pull
          - name: datanetworks
            group: req.nephio.org/v1alpha1
            mode: pull
          - name: interfaces
            group: req.nephio.org/v1alpha1
            mode: pull
          - name: rawtopologies
            group: topo.nephio.org/v1alpha1
            mode: pull
          - name: vlanclaims
            group: vlan.resource.nephio.org/v1alpha1
            mode: pull
          - name: vlanindices
            group: vlan.resource.nephio.org/v1alpha1
            mode: pull
          - name: vlans
            group: vlan.resource.nephio.org/v1alpha1
            mode: pull
          - name: amfdeployments
            group: workload.nephio.org/v1alpha1
            mode: pull
          - name: smfdeployments
            group: workload.nephio.org/v1alpha1
            mode: pull
          - name: upfdeployments
            group: workload.nephio.org/v1alpha1
            mode: pull
          - name: clusters
            group: cluster.x-k8s.io
            mode: pull

    processors:
      batch:
        send_batch_size: 10000
        timeout: 1s

      attributes/add-source/k8s_cluster:
        actions:
          - key: otel_data_source
            value: k8s_cluster
            action: upsert

      attributes/add-source/k8sobjects:
        actions:
          - key: otel_data_source
            value: k8sobjects
            action: upsert

      attributes/cluster:
        actions:
          - key: cluster_name
            value: ${env:CLUSTER_NAME}
            action: upsert
          - key: region
            value: ${env:REGION}
            action: upsert
          - key: site_type
            value: ${env:SITE_TYPE}
            action: upsert

    exporters:
      debug:

      prometheusremotewrite/remote:
        endpoint: "http://10.254.185.27:9009/api/v1/push"
        tls:
          insecure: true

      prometheusremotewrite/edge:
        endpoint: "http://cnos-prometheus-agent-local.cnos-system:8080/api/v1/write"
        tls:
          insecure: true

      otlp/jaeger-edge:
        endpoint: http://cnos-jaeger-collector.cnos-system:4317
        tls:
          insecure: true

      otlp/jaeger-remote:
        endpoint: http://10.254.185.27:4317
        tls:
          insecure: true

      otlp/elasticsearch-edge:
        endpoint: http://cnos-apm-server:8200
        tls:
          insecure: true

      otlp/elasticsearch-remote:
        endpoint: http://10.254.185.27:8200
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, attributes/cluster]
          exporters: [debug, otlp/jaeger-edge, otlp/jaeger-remote]

        metrics:
          receivers: [otlp]
          processors: [batch, attributes/cluster]
          exporters: [debug, prometheusremotewrite/remote, prometheusremotewrite/edge]
        metrics/k8s_cluster:
          receivers: [k8s_cluster]
          processors: [batch, attributes/cluster, attributes/add-source/k8s_cluster]
          exporters: [debug, prometheusremotewrite/remote, prometheusremotewrite/edge]

        logs:
          receivers: [otlp]
          processors: [batch, attributes/cluster]
          exporters: [debug, otlp/elasticsearch-edge, otlp/elasticsearch-remote]
        logs/k8sobjects:
          receivers: [k8sobjects]
          processors: [batch, attributes/cluster, attributes/add-source/k8sobjects]
          exporters: [debug, otlp/elasticsearch-edge, otlp/elasticsearch-remote]
